modLoader="javafml"
loaderVersion="[37,)" 
license="All Rights Reserved"

[[mods]] 
modId="teraphobia" 
version="1.0.0" 
displayName="Teraphobia" 
logoFile="icon.png" 
credits="https://github.com/nvb-uy/Teraphobia" 
authors="ElocinDev" 
description='''
The core mod of the Fear Nightfall modpack. Adds core functionality for the modpack.
'''
[[dependencies.teraphobia]]
    modId="forge" 
    mandatory=true 
    versionRange="[37,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.teraphobia]]
    modId="luna" 
    mandatory=false 
    versionRange="[0,)" 
    ordering="NONE"
    side="CLIENT"