modLoader="javafml"
loaderVersion="[37,)" 
license="AGNYA License"

[[mods]] 
modId="teraphobia" 
version="1.0.0" 
displayName="Teraphobia" 
logoFile="icon.png" 
credits="https://github.com/nvb-uy" 
authors="ElocinDev" 
description='''
A scary mod made for the Fear Nightfall modpack.
'''
[[dependencies.teraphobia]] #optional
    modId="forge" 
    mandatory=true 
    versionRange="[37,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.teraphobia]] #optional
    modId="luna" 
    mandatory=true 
    versionRange="[0,)" 
    ordering="NONE"
    side="CLIENT"